<?php

namespace ForumBundle\Repository;

/**
 * SujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetRepository extends \Doctrine\ORM\EntityRepository
{
    public function nbresujetsignale()
    {
        return $this->createQueryBuilder('r')
            ->select('COUNT(r)')
            ->where('r.strike >=10' )
            ->getQuery()
            ->getSingleScalarResult();
    }


    public function signaler()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM ForumBundle:sujet c WHERE c.strike >=10 ");
        return $query->getResult();
    }
}
